### ISSUE TITLE
Hello ! 

### ISSUE THREAD

**Issue by League2EB** [DeluxeAlonso/UpcomingMovies#34]
Dear developer,
I would like to ask whether this App has been released to the App Store?
I think it's practical and I love movies

**Comment by DeluxeAlonso** [comment]
Hi @League2EB! I currently  have no plans to upload it to the AppStore in the near future. Im going to keep adding new feature and then will evaluate if its worth to release it.

Im glad you find it practical! Im open to new feature proposals if you have one in mind.

**Comment by League2EB** [comment]
Ok, I will try to give advice
I also hope it can be successfully put on the App Store in the future, looking forward to it
