### ISSUE TITLE
Steps to follow the code

### ISSUE THREAD

**Issue by Prashant-Swift** [DeluxeAlonso/UpcomingMovies#746]
Hi  this  code is very impressive , in my projects I just used simple MVC / MVVM , 
I really want to learn this 
for me  I am facing difficulties to follow the architecture 
What is the first step to do to implement such a architecture 
Did you identify all dependency earlier before code how to do that 

I apologies  if it is  difficult to understand my question (English )

**Comment by DeluxeAlonso** [comment]
Hey @Prashant-Smilefy I will be working on a detailed explanation of how everything works with the app and expect to release it soon.

To get a better grasp on how I built this app you can take a look at this article: https://tech.olx.com/clean-architecture-and-mvvm-on-ios-c9d167d9f5b3 which explains the architecture used here (it even has an example using a movies app). It is not exactly the same but the basics are very similar.

Three main layers: Presentation, Domain, Data, and everything is glued in our DIContainer class. If you have any specific questions don't hesitate to contact me. I will be glad to help you.

**Comment by Prashant-Swift** [comment]
@DeluxeAlonso  Thank you ❤️
